/* Pathway A · "Learn to use the tool" interactive tutorial, content.

   Two worked examples, same three stages, opposite order:
     Example 1 · David   teaching-first    sequence  -> mapping -> rubric
     Example 2 · Priya   assessment-first  mapping   -> rubric  -> sequence

   Every figure is checked against a real capture in assets/priya/ or derived
   from the scenario source data. Derivations worth knowing:
     · Priya's Tab 5 totals come straight from the captures (21.75 / 28.00 / 50.25).
     · David's CLO weightings (30 / 25 / 25 / 20) are the set that reproduces his
       published 28 / 34 / 38 exactly; his Tab 6 figures are computed from them.
     · NOTE the two Priya Tab 6 captures are filename-swapped: t6-after.png holds
       the BEFORE composition and t6-before.png holds the AFTER composition.

   Block kinds:
     {k:'brief'}   context + the figures the CD is given
     {k:'entry'}   fields the CD types in; `expect` gates the advance
                   `derive:true` means there is no panel to copy, they work it out
     {k:'result'}  what the tool then shows (shot: real capture, or readout: table)
     {k:'probe'}   reveal-first diagnostic, then a question-bank prompt (qb: entry id)
     {k:'note'}    narration, optionally carrying a named principle              */
(function () {

  const P = 'assets/priya/';

  /* ─── Example 1 · David · History · teaching-first ─── */

  const DAVID = {
    id: 'david',
    eyebrow: 'Example 1 · Teaching-first',
    title: 'Starting from the teaching sequence',
    discipline: 'History · new course · Relative Emphasis',
    blurb: "David builds the teaching sequence first and lets the mapping describe it. This is the order the tool is designed around: fill in the Teaching Readiness template, then map demand against a readiness picture that already exists. You will do all three stages, sequence then mapping then rubric, and in Example 2 you will do exactly the same three in reverse.",
    iterations: [
      {
        n: 1,
        title: 'The sequence',
        aim: 'Set the course weightings, then build the weekly teaching sequence in Tab 2 so that readiness exists before anything is mapped against it.',
        blocks: [
          { k: 'brief',
            title: 'The course you are working with',
            body: [
              'David is designing a new History course with three assignments: a source analysis in Week 4 at 25%, an essay in Week 8 at 35%, and a research portfolio in Week 12 at 40%.',
              'As a new course there is nothing already running to check against, so he and his learning designer build the teaching sequence as part of the design itself. Start with Tab 1, which sets how much of the course each outcome is worth.',
            ],
            figures: {
              title: 'Tab 1 · CLO Weightings, the figures to enter',
              cols: ['CLO', 'Course weighting'],
              rows: [
                ['CLO 1 · historical reasoning', '30%'],
                ['CLO 2 · source analysis and evaluation', '25%'],
                ['CLO 3 · historiographical understanding', '25%'],
                ['CLO 4 · research and argumentation', '20%'],
              ],
            },
          },
          { k: 'entry',
            tab: 'Tab 1',
            title: 'Enter the CLO weightings',
            unit: '%',
            groups: [{ label: 'Course weighting', inputs: [
              { id: 'd1c1', label: 'CLO 1', expect: 30 },
              { id: 'd1c2', label: 'CLO 2', expect: 25 },
              { id: 'd1c3', label: 'CLO 3', expect: 25 },
              { id: 'd1c4', label: 'CLO 4', expect: 20 },
            ] }],
          },
          { k: 'brief',
            title: 'Tab 2, the Teaching Readiness Mapping Template',
            body: [
              'This is where the teaching sequence is recorded, week by week. For each week you note the teaching focus, attach the outcomes that week genuinely works on, and set how far each one has been taught by the end of it: Foundational, Developing, or Complete.',
              'Readiness carries forward. Once an outcome reaches a level it cannot drop back later in the course. What you record here populates the Readiness row of the mapping automatically, which is why doing it first is the smoother order.',
              "Here are the first four weeks of David's sequence, and what each outcome has reached by the end of Week 4.",
            ],
            figures: {
              title: 'Tab 2 · Weeks 1 to 4',
              cols: ['Week', 'Teaching focus', 'Builds'],
              rows: [
                ['Week 1', 'Introduction to historical thinking', 'CLO 1, CLO 3'],
                ['Week 2', 'Provenance, reliability, reading against the grain', 'CLO 2'],
                ['Week 3', 'Constructing a historical argument', 'CLO 4'],
                { c: ['Week 4', 'Source analysis due', 'first assessment point'], k: 'asg' },
              ],
              note: 'David front-loads CLO 2 deliberately. The source analysis is the assignment it exists for, so the provenance workshop has to land before it, not after.',
            },
          },
          { k: 'brief',
            title: 'What the sequence delivers by Week 4',
            body: ['Enter the readiness each outcome has reached by the end of Week 4, the week the source analysis falls in.'],
            figures: {
              title: 'Tab 2 · readiness at Week 4, the figures to enter',
              cols: ['CLO', 'Level', 'Readiness'],
              rows: [
                ['CLO 1 · historical reasoning', 'Developing', '40%'],
                ['CLO 2 · source analysis and evaluation', 'Developing', '65%'],
                ['CLO 3 · historiographical understanding', 'Foundational', '20%'],
                ['CLO 4 · research and argumentation', 'Foundational', '35%'],
              ],
            },
          },
          { k: 'entry',
            tab: 'Tab 2',
            title: 'Record readiness at Week 4',
            unit: '%',
            groups: [{ label: 'Taught by Week 4', inputs: [
              { id: 'd2r1', label: 'CLO 1', expect: 40 },
              { id: 'd2r2', label: 'CLO 2', expect: 65 },
              { id: 'd2r3', label: 'CLO 3', expect: 20 },
              { id: 'd2r4', label: 'CLO 4', expect: 35 },
            ] }],
          },
          { k: 'note',
            body: [
              'That is the teaching-first order in one move. The readiness picture now exists, so when you open the mapping in a moment the Readiness row will already be populated and every bar will have something in it.',
              'Hold on to that, because Example 2 shows you what the same tab looks like when the template has been skipped, and the difference is the whole point of this tutorial.',
            ],
          },
        ],
      },
      {
        n: 2,
        title: 'The mapping',
        aim: 'Enter relative emphasis rather than percentages, read the implied assignment structure, and find out how differently the conservation principle behaves when the numbers are ratios.',
        blocks: [
          { k: 'brief',
            title: 'Relative emphasis, not percentages',
            body: [
              "David does not know exact shares, but he knows relative importance with confidence. Tab 4 lets him rate each assignment's importance for each outcome from 1 to 10 and converts the ratios itself.",
              'Read his ratings before you enter them. CLO 2 at the source analysis is a 9, the strongest rating anywhere in the mapping, which is exactly what you would expect given he sequenced the provenance workshop into Week 2 to support it.',
            ],
            figures: {
              title: 'Tab 4 · Relative Emphasis, the figures to enter',
              cols: ['CLO', 'Source analysis', 'Essay', 'Portfolio'],
              rows: [
                ['CLO 1 · historical reasoning', '5', '8', '7'],
                ['CLO 2 · source analysis and evaluation', '9', '5', '3'],
                ['CLO 3 · historiographical understanding', '3', '6', '9'],
                ['CLO 4 · research and argumentation', '3', '5', '9'],
              ],
              note: 'A rating means nothing on its own, only against the other two in its row.',
            },
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: 'Enter the emphasis ratings',
            columns: ['Source analysis', 'Essay', 'Portfolio'],
            groups: [
              { label: 'CLO 1', inputs: [{ id: 'd4a1', expect: 5 }, { id: 'd4a2', expect: 8 }, { id: 'd4a3', expect: 7 }] },
              { label: 'CLO 2', inputs: [{ id: 'd4b1', expect: 9 }, { id: 'd4b2', expect: 5 }, { id: 'd4b3', expect: 3 }] },
              { label: 'CLO 3', inputs: [{ id: 'd4c1', expect: 3 }, { id: 'd4c2', expect: 6 }, { id: 'd4c3', expect: 9 }] },
              { label: 'CLO 4', inputs: [{ id: 'd4d1', expect: 3 }, { id: 'd4d2', expect: 5 }, { id: 'd4d3', expect: 9 }] },
            ],
          },
          { k: 'result',
            tab: 'Tab 4 · readiness check',
            readout: {
              title: 'Every bar clears its marker at the source analysis',
              cols: ['CLO', 'Demand claims', 'Minimum readiness', 'Sequence delivers'],
              rows: [
                ['CLO 1', '25% of its budget', '25%', '40%'],
                ['CLO 2', '53% of its budget', '53%', '65%'],
                ['CLO 3', '17% of its budget', '17%', '20%'],
                ['CLO 4', '18% of its budget', '18%', '35%'],
              ],
              note: 'No warnings. Because the sequence went in first, the readiness bars were already populated when the demand arrived, and every one of them sits past its minimum.',
            },
          },
          { k: 'note',
            body: ["Worth naming what just did not happen. There was no conflict to resolve, no warning to interpret, and no decision about whether to move teaching or lower demand. That is not luck: David built a sequence that front-loads the outcome his first assignment leans on hardest, then mapped against it. Example 2 arrives at the same place by the long road."] },
          { k: 'result',
            tab: 'Tab 5 · Assignment Weightings',
            readout: {
              title: 'What the ratios convert to',
              cols: ['CLO', 'Source analysis', 'Essay', 'Research portfolio'],
              rows: [
                ['CLO 1', '7.50%', '12.00%', '10.50%'],
                ['CLO 2', '13.24%', '7.35%', '4.41%'],
                ['CLO 3', '4.17%', '8.33%', '12.50%'],
                ['CLO 4', '3.53%', '5.88%', '10.59%'],
              ],
              totals: ['28.44%', '33.56%', '38.00%'],
              note: 'Grand total 100.00%',
            },
            headline: { label: 'Implied distribution (source analysis / essay / portfolio)', value: '28.44 / 33.56 / 38.00', note: 'against the fixed 25 / 35 / 40' },
          },
          { k: 'probe',
            question: 'Three points over on the source analysis, one and a half under on the essay, two under on the portfolio. Does this need fixing? What would you ask before deciding?',
            qb: 'dont-want-to-adjust',
            why: 'Because the answer is very often no, and a shrug is not the same as a decision. What the review record needs is not the gap, it is the academic saying out loud what tolerance they accept and why.',
          },
          { k: 'note',
            body: ["David's answer: “The ordering's right, the source analysis is lightest, the portfolio's heaviest. The source analysis pulling a bit higher makes sense too: CLO 2's a 9 there, the strongest rating in the whole mapping. If this were ten points off I'd want to know why. Three points, I trust the mapping.”"] },
          { k: 'brief',
            title: 'But suppose the essay had to move',
            body: [
              "Imagine his department asks for the essay to carry more. His instinct is the obvious one: raise the essay rating in every row by two, so the essay matters more everywhere.",
              'Enter that and see whether "more everywhere" behaves the way it sounds.',
            ],
            figures: {
              title: 'Tab 4 · every essay rating raised by 2',
              cols: ['CLO', 'Source analysis', 'Essay', 'Portfolio'],
              rows: [
                ['CLO 1', '5', '10', '7'],
                ['CLO 2', '9', '7', '3'],
                ['CLO 3', '3', '8', '9'],
                ['CLO 4', '3', '7', '9'],
              ],
            },
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: 'Raise every essay rating by two',
            columns: ['Source analysis', 'Essay', 'Portfolio'],
            groups: [
              { label: 'CLO 1', inputs: [{ id: 'd4e1', expect: 5 }, { id: 'd4e2', expect: 10 }, { id: 'd4e3', expect: 7 }] },
              { label: 'CLO 2', inputs: [{ id: 'd4f1', expect: 9 }, { id: 'd4f2', expect: 7 }, { id: 'd4f3', expect: 3 }] },
              { label: 'CLO 3', inputs: [{ id: 'd4g1', expect: 3 }, { id: 'd4g2', expect: 8 }, { id: 'd4g3', expect: 9 }] },
              { label: 'CLO 4', inputs: [{ id: 'd4h1', expect: 3 }, { id: 'd4h2', expect: 7 }, { id: 'd4h3', expect: 9 }] },
            ],
          },
          { k: 'result',
            tab: 'Tab 5 · after raising every essay rating',
            readout: {
              title: 'What the ratios convert to now',
              cols: ['CLO', 'Source analysis', 'Essay', 'Research portfolio'],
              rows: [
                ['CLO 1', '6.82%', '13.64%', '9.55%'],
                ['CLO 2', '11.84%', '9.21%', '3.95%'],
                ['CLO 3', '3.75%', '10.00%', '11.25%'],
                ['CLO 4', '3.16%', '7.37%', '9.47%'],
              ],
              totals: ['25.57%', '40.22%', '34.21%'],
              note: 'Grand total 100.00%',
            },
            headline: { label: 'Implied distribution', value: '25.57 / 40.22 / 34.21', note: 'the essay has overshot 35 by five points, and the portfolio has fallen six points below 40' },
          },
          { k: 'probe',
            question: 'David asked for the essay to carry more and it now carries far too much, while the portfolio, which he never touched, has collapsed. Where did the portfolio\u2019s weight go?',
            qb: 'weight-has-to-move',
            why: 'Because it stops the vague intention to make something heavier and turns it into a directional decision that can be checked: which outcome, and which assignment gives the weight up.',
          },
          { k: 'note',
            body: [
              "Nothing was added. Raising the essay rating in all four rows raised the essay's share of all four budgets at once, and every point of that came out of the source analysis and the portfolio. The accumulation problem and the conservation problem arriving together.",
              "The targeted fix is one number. David lowers CLO 2's source analysis rating from 9 to 6 and leaves everything else at its original value.",
            ],
            principle: { name: 'Conservation of alignment, in ratio form', text: "A relative emphasis rating has no absolute meaning, only a share of its own row. Changing one rating redistributes that entire row, so there is no such thing as a local edit. Raising the same column everywhere is not a neutral move; it is the same move made four times." },
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: "Revert, then lower CLO 2's source analysis rating",
            columns: ['Source analysis', 'Essay', 'Portfolio'],
            groups: [
              { label: 'CLO 1', inputs: [{ id: 'd4i1', expect: 5 }, { id: 'd4i2', expect: 8 }, { id: 'd4i3', expect: 7 }] },
              { label: 'CLO 2', inputs: [{ id: 'd4j1', expect: 6 }, { id: 'd4j2', expect: 5 }, { id: 'd4j3', expect: 3 }] },
              { label: 'CLO 3', inputs: [{ id: 'd4k1', expect: 3 }, { id: 'd4k2', expect: 6 }, { id: 'd4k3', expect: 9 }] },
              { label: 'CLO 4', inputs: [{ id: 'd4l1', expect: 3 }, { id: 'd4l2', expect: 5 }, { id: 'd4l3', expect: 9 }] },
            ],
          },
          { k: 'result',
            tab: 'Tab 5 · one rating changed',
            readout: {
              title: 'One number, three totals',
              cols: ['CLO', 'Source analysis', 'Essay', 'Research portfolio'],
              rows: [
                ['CLO 1', '7.50%', '12.00%', '10.50%'],
                ['CLO 2', '10.71%', '8.93%', '5.36%'],
                ['CLO 3', '4.17%', '8.33%', '12.50%'],
                ['CLO 4', '3.53%', '5.88%', '10.59%'],
              ],
              totals: ['25.91%', '35.14%', '38.95%'],
              note: 'Grand total 100.00%',
            },
            headline: { label: 'Implied distribution', value: '25.91 / 35.14 / 38.95', note: 'against the fixed 25 / 35 / 40, every assignment within a point' },
          },
          { k: 'note',
            body: [
              "One rating, lowered by three, moved all three assignments onto their targets. The failed attempt moved twelve ratings and made the mapping worse. The difference was not effort; it was knowing which row the weight had to come out of.",
              "One thing to check before moving on: lowering CLO 2 at the source analysis dropped its claim on that outcome from 53% to 43%, so the minimum readiness fell too. The sequence delivers 65%, so it still clears comfortably. Demand changes move the markers, and the markers are what the sequence has to satisfy.",
            ],
          },
        ],
      },
      {
        n: 3,
        title: 'The rubric',
        aim: 'Tab 6 reads composition straight off the finalised mapping. See what it asks of a rubric that has not been written yet, and what happens when one criterion carries two outcomes.',
        blocks: [
          { k: 'brief',
            title: 'What Tab 6 does',
            body: [
              'Tab 5 tells you what each assignment is worth overall. Tab 6 tells you what each outcome should be worth inside it. For a new course that is genuinely useful: David has not written the rubric yet, so this is a specification rather than an audit.',
              'Here is what the finalised mapping asks of the source analysis.',
            ],
            figures: {
              title: 'Tab 6 · source analysis composition',
              cols: ['CLO', 'Should attract'],
              rows: [
                ['CLO 1 · historical reasoning', '28.9%'],
                ['CLO 2 · source analysis and evaluation', '41.3%'],
                ['CLO 3 · historiographical understanding', '16.1%'],
                ['CLO 4 · research and argumentation', '13.7%'],
              ],
              note: 'Only CLO 2 moved during the mapping stage, so only this assignment needs a close look. Its composition shifted by five points; the essay and portfolio moved by three and two.',
            },
          },
          { k: 'brief',
            title: 'The rubric David has drafted',
            body: ['Three criteria, 100 marks. Note the first one: it carries two outcomes at once.'],
            figures: {
              title: 'Draft rubric · source analysis, 100 marks',
              cols: ['Criterion', 'Marks', 'Mapped to'],
              rows: [
                ['Contextual reading and historiographical framing', '40', 'CLO 1 + CLO 3'],
                ['Evaluation of provenance and reliability', '45', 'CLO 2'],
                ['Clarity of written argument', '15', 'CLO 4'],
              ],
            },
          },
          { k: 'probe',
            question: 'The first criterion is worth 40 marks and carries two outcomes. Tab 6 asks for 28.9% and 16.1% from them. Before you do any arithmetic: what do you need to know from David that the rubric does not tell you?',
            qb: 'implicit-weighting',
            why: 'Because a criterion carrying two outcomes has an internal weighting between them that has never been written down anywhere. David will have one, he applies it every time he marks, and until it is said out loud the rubric cannot be checked against anything. Ask how he marks it in practice, not how it should be marked.',
          },
          { k: 'note',
            body: ["David's answer is the one most people give first: “About half and half, I suppose.” Fifty-fifty across 40 marks gives CLO 1 20% of the assignment and CLO 3 20%. Against Tab 6's 28.9% and 16.1%, the first is nine points light and the second four points heavy, inside a single criterion that looked perfectly reasonable."] },
          { k: 'brief',
            title: 'Two numbers to fix',
            body: [
              'The two outcomes in that criterion need 28.9% and 16.1%, which is 45% of the assignment between them. The criterion is only worth 40 marks, so it is the wrong size as well as the wrong shape.',
              'Set it to 45 marks split 64 / 36 internally, and take the difference off the other two criteria in proportion to what Tab 6 asks of them.',
            ],
            figures: {
              title: 'The corrected rubric',
              cols: ['Criterion', 'Marks', 'Internal balance'],
              rows: [
                ['Contextual reading and historiographical framing', '45', '64% CLO 1 / 36% CLO 3'],
                ['Evaluation of provenance and reliability', '41', 'CLO 2 only'],
                ['Clarity of written argument', '14', 'CLO 4 only'],
              ],
              note: 'Each outcome now lands within a fraction of a point of Tab 6.',
            },
          },
          { k: 'entry',
            tab: 'Tab 6',
            title: 'Enter the corrected marks',
            groups: [{ label: 'Marks', inputs: [
              { id: 'd6m1', label: 'Contextual reading and historiographical framing', expect: 45 },
              { id: 'd6m2', label: 'Evaluation of provenance and reliability', expect: 41 },
              { id: 'd6m3', label: 'Clarity of written argument', expect: 14 },
            ] }],
          },
          { k: 'note',
            body: [
              "The rubric now matches the mapping, and David has something he did not have before: a stated reason why the provenance criterion is worth 41 marks rather than 45. Not a preference, a consequence of the emphasis ratings he set in Tab 4.",
              "He also has a decision waiting. A criterion asking markers to weigh two different things at 64 / 36 is harder to apply consistently than one doing a single job. Splitting it into two criteria would make the weighting explicit rather than internal. That is a rubric-design judgement, not a numbers one, and it is better made now while the course is still being written than after it has run.",
            ],
            principle: { name: 'Multi-mapped criteria', text: 'A criterion mapped to more than one outcome carries an implicit weighting between them that has never been stated. Asking how the criterion is actually marked surfaces it, and it is very often the entire explanation for a gap against Tab 6.' },
          },
        ],
      },
    ],
  };

  /* ─── Example 2 · Priya · Nursing · assessment-first ─── */

  const PRIYA = {
    id: 'priya',
    eyebrow: 'Example 2 · Assessment-first',
    title: 'Starting from the assessment structure',
    discipline: 'Nursing · third year · Direct method',
    blurb: "Priya goes the other way. She maps what each assignment assesses first, settles the rubric against it, and only then designs the teaching sequence that has to deliver it. Same three stages as Example 1, reversed, and with real captures of the tool at every step.",
    iterations: [
      {
        n: 1,
        title: 'The mapping',
        aim: 'Enter the weightings and the demand, read the implied assignment structure, and find out why an isolated fix makes things worse.',
        blocks: [
          { k: 'brief',
            title: 'The course you are working with',
            body: [
              'Priya coordinates a third-year Nursing course with three assignments: a clinical reflection in Week 4, a care plan in Week 8, and a case study exam in Week 10. The course has been taught and described to students as a 20 / 40 / 40 distribution across those three for several years.',
              'She has four course learning outcomes, and a strong instinct about one of them: clinical reasoning only shows its true depth under pressure, so the exam is where it should really be tested.',
              'Unlike David, she is going straight to the mapping. The Teaching Readiness template stays empty for now, which will matter shortly.',
            ],
            figures: {
              title: 'Tab 1 · CLO Weightings, the figures to enter',
              cols: ['CLO', 'Course weighting'],
              rows: [
                ['CLO 1 · clinical reasoning', '30%'],
                ['CLO 2 · patient-centred care', '25%'],
                ['CLO 3 · evidence-based practice', '30%'],
                ['CLO 4 · professional communication', '15%'],
              ],
            },
          },
          { k: 'entry',
            tab: 'Tab 1',
            title: 'Enter the CLO weightings',
            body: ['Type each weighting into the tool. They total 100%.'],
            unit: '%',
            groups: [{ label: 'Course weighting', inputs: [
              { id: 'p1c1', label: 'CLO 1', expect: 30 },
              { id: 'p1c2', label: 'CLO 2', expect: 25 },
              { id: 'p1c3', label: 'CLO 3', expect: 30 },
              { id: 'p1c4', label: 'CLO 4', expect: 15 },
            ] }],
          },
          { k: 'brief',
            title: 'What Priya wants the assignments to do',
            body: ['In Tab 4 she uses the Direct approach: each outcome gets its own 100%, distributed across the three assignments. The numbers below are the ones she entered on her first attempt. They follow her instinct directly, with clinical reasoning held back for the exam.'],
            figures: {
              title: 'Tab 4 · Demand, the figures to enter',
              cols: ['CLO', 'Clinical reflection', 'Care plan', 'Case study exam'],
              rows: [
                ['CLO 1 · clinical reasoning', '15', '15', '70'],
                ['CLO 2 · patient-centred care', '30', '40', '30'],
                ['CLO 3 · evidence-based practice', '15', '25', '60'],
                ['CLO 4 · professional communication', '35', '40', '25'],
              ],
              note: "Each row is that outcome's own 100%, distributed across the three assignments.",
            },
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: 'Enter the demand, row by row',
            body: ['Four rows, three assignments each. Entering them one row at a time is exactly how Priya entered them, and part of why what comes next surprised her.'],
            columns: ['Reflection', 'Care plan', 'Exam'],
            groups: [
              { label: 'CLO 1', inputs: [{ id: 'p4a1', expect: 15 }, { id: 'p4a2', expect: 15 }, { id: 'p4a3', expect: 70 }] },
              { label: 'CLO 2', inputs: [{ id: 'p4b1', expect: 30 }, { id: 'p4b2', expect: 40 }, { id: 'p4b3', expect: 30 }] },
              { label: 'CLO 3', inputs: [{ id: 'p4c1', expect: 15 }, { id: 'p4c2', expect: 25 }, { id: 'p4c3', expect: 60 }] },
              { label: 'CLO 4', inputs: [{ id: 'p4d1', expect: 35 }, { id: 'p4d2', expect: 40 }, { id: 'p4d3', expect: 25 }] },
            ],
          },
          { k: 'result',
            tab: 'Tab 4 · as entered',
            shot: P + 't4-first-v2.png',
            alt: "The tool's CLO Mapping tab with Priya's first-attempt demand values entered: CLO 1 at 15, 15, 70; CLO 2 at 30, 40, 30; CLO 3 at 15, 25, 60; CLO 4 at 35, 40, 25. Every readiness bar reads 0% and Not taught, with a minimum readiness marker on each.",
            cap: 'Look at the Readiness row: every bar reads 0% and Not taught. That is not an error, and it is the price of skipping Tab 2. The tool has no teaching sequence to draw on, so it can show you only half the picture.',
            caveat: 'What it can already give you is the marker on each bar: the minimum readiness that the demand you just entered will require. Those markers are the specification your teaching sequence will have to meet, and Iteration 3 is where you go and meet them.',
          },
          { k: 'result',
            tab: 'Tab 5 · Assignment Weightings',
            shot: P + 't5-first.png',
            alt: 'The Assignment Weightings tab showing every CLO contribution per assignment and the assignment totals: 21.75%, 28.00% and 50.25%.',
            cap: 'Tab 5 reads off what you just entered. Nothing here was typed in directly.',
            headline: { label: 'Implied distribution (reflection / care plan / exam)', value: '21.75 / 28.00 / 50.25', note: 'against the 20 / 40 / 40 the course has been taught to for years' },
          },
          { k: 'probe',
            question: 'The exam is carrying ten points more than the course says it does, and the care plan twelve points less. Does that match the structure you were given? If not, what is the first question you would ask Priya?',
            qb: 'sum-of-rows',
            why: 'Because the number is not a mistake to be corrected, it is a total to be read. Nobody entered 50.25. It is the sum of four separate, individually reasonable judgements, and the academic is the only person who can say which of their own rows produced it.',
          },
          { k: 'note',
            body: ['Priya went back through her four rows and found it herself: clinical reasoning, evidence-based practice and professional communication were all leaning toward the exam. Three rows out of four, each entered separately, none of them unreasonable on its own.'],
            principle: { name: 'Demand accumulation', text: 'Tab 5 is the sum of every CLO row in Tab 4. No single row has to look wrong for the total to be wrong. Five per cent here and five per cent there accumulates fast, and it accumulates invisibly while you are entering one row at a time.' },
          },
          { k: 'brief',
            title: 'Priya tries a fix',
            body: [
              'She wants the exam lighter, and clinical reasoning is the row she loaded hardest toward it. So she gets more deliberate about her original intention and pushes it further: 5 / 10 / 85.',
              'Enter her revision and see what it does.',
            ],
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: 'Revise CLO 1 only',
            columns: ['Reflection', 'Care plan', 'Exam'],
            groups: [{ label: 'CLO 1', inputs: [{ id: 'p4e1', expect: 5 }, { id: 'p4e2', expect: 10 }, { id: 'p4e3', expect: 85 }] }],
            body: ['Leave CLO 2, CLO 3 and CLO 4 exactly as they are.'],
          },
          { k: 'result',
            tab: 'Tab 5 · after the revision',
            shot: P + 't5-second.png',
            alt: 'The Assignment Weightings tab after the CLO 1 revision, showing assignment totals of 18.75%, 26.50% and 54.75%.',
            cap: 'The exam has gone up, not down.',
            headline: { label: 'Implied distribution', value: '18.75 / 26.50 / 54.75', note: 'was 21.75 / 28.00 / 50.25, every assignment moved the wrong way' },
          },
          { k: 'probe',
            question: 'Priya reduced clinical reasoning in two places and the exam grew by four and a half points. Before reading on: can you say why?',
            qb: 'went-up-without',
            why: 'Because this is the most productive moment in a session, and the instinct is to rescue it. Do not. The academic who diagnoses their own directional error rarely makes it again; the academic who is told what went wrong has learned a fact about this mapping rather than a rule about all of them.',
          },
          { k: 'note',
            body: ["Priya's own words: “I moved it the wrong way. I wanted the exam lighter, so I should have increased clinical reasoning's share at the reflection or the care plan instead, that's what would have pulled the exam's share down. Reducing the other two just gave the exam more room to grow.”"],
            principle: { name: 'Conservation of alignment', text: "Within any one outcome's row, the shares are drawn from that outcome's own fixed budget: increasing its share in one assignment necessarily decreases it elsewhere in the row. The direction matters. To reduce an assignment's total, increase that outcome's influence in the other assignments. To increase it, reduce that outcome's influence elsewhere." },
          },
          { k: 'brief',
            title: 'The revision that works',
            body: [
              "Kate, the learning designer, asks her to separate two things she has collapsed: when an outcome is fully demonstrable under pressure, and when it is ready to be assessed at all. Priya's original row treated the care plan almost the same as the reflection, both low, everything held for the exam, when the care plan is well placed to carry real clinical reasoning.",
              'Three rows change. CLO 4 is the interesting one: professional communication is fully taught and consolidated by the care plan, so Priya sets the exam to zero. That is a deliberate zero, a claim that the assessment work is already complete, not a gap.',
            ],
            figures: {
              title: 'Tab 4 · the revised rows',
              cols: ['CLO', 'Reflection', 'Care plan', 'Exam'],
              rows: [
                ['CLO 1 · clinical reasoning', '15', '40', '45'],
                ['CLO 3 · evidence-based practice', '10', '35', '55'],
                ['CLO 4 · professional communication', '45', '55', '0'],
              ],
              note: 'CLO 2 does not move.',
            },
          },
          { k: 'entry',
            tab: 'Tab 4',
            title: 'Enter the three revised rows',
            columns: ['Reflection', 'Care plan', 'Exam'],
            groups: [
              { label: 'CLO 1', inputs: [{ id: 'p4f1', expect: 15 }, { id: 'p4f2', expect: 40 }, { id: 'p4f3', expect: 45 }] },
              { label: 'CLO 3', inputs: [{ id: 'p4g1', expect: 10 }, { id: 'p4g2', expect: 35 }, { id: 'p4g3', expect: 55 }] },
              { label: 'CLO 4', inputs: [{ id: 'p4h1', expect: 45 }, { id: 'p4h2', expect: 55 }, { id: 'p4h3', expect: 0 }] },
            ],
          },
          { k: 'result',
            tab: 'Tab 4 · full revision',
            shot: P + 't4-revision-v2.png',
            alt: 'CLO Mapping after the full revision: CLO 1 at 15, 40, 45; CLO 2 unchanged at 30, 40, 30; CLO 3 at 10, 35, 55; CLO 4 at 45, 55, 0. All readiness bars still read 0% and Not taught, and each minimum readiness marker has moved.',
            cap: 'Every minimum readiness marker has moved, because you changed the demand that sets them. CLO 4 now needs 45% taught by the clinical reflection, where before it needed 35%.',
          },
          { k: 'result',
            tab: 'Tab 5 · final',
            shot: P + 't5-final.png',
            alt: 'The Assignment Weightings tab after the full revision, showing assignment totals of 21.75%, 40.75% and 37.50%.',
            headline: { label: 'Implied distribution', value: '21.75 / 40.75 / 37.50', note: 'against the intended 20 / 40 / 40, close enough for Priya to build around' },
          },
        ],
      },
      {
        n: 2,
        title: 'The rubric',
        aim: 'The mapping has settled, so the rubric can be checked against it. Find out why an assignment whose total barely moved can still need its rubric rewritten.',
        blocks: [
          { k: 'brief',
            title: 'Where the rubric check belongs',
            body: [
              'Tab 6 reads composition straight off the mapping, so it is only worth opening once Tab 4 has stopped moving. It has now.',
              'Three of Priya\u2019s four rows changed during Iteration 1: CLO 1, CLO 3 and CLO 4. Only CLO 2 stayed put, which means every one of her three assignments has had its rubric composition shift somewhere.',
            ],
          },
          { k: 'probe',
            question: "Start with the clinical reflection. Its overall weighting in Tab 5 is 21.75% before and 21.75% after: identical. Does that mean its rubric needs no second look?",
            qb: 'stable-total-shifted-rubric',
            why: 'Because the rubric check is scoped by which rows moved, not by which totals moved. An assignment whose total is unchanged can have two outcomes trading several points inside it, and it is the one an academic will confidently skip.',
          },
          { k: 'result',
            tab: 'Tab 6 · before',
            shot: P + 't6-after.png',
            alt: 'The Marking Guide and Rubric Composition tab showing the composition derived from the original demand values, with the clinical reflection at CLO 1 20.7%, CLO 2 34.5%, CLO 3 20.7%, CLO 4 24.1%.',
            cap: 'Composition derived from the original demand values.',
          },
          { k: 'result',
            tab: 'Tab 6 · after',
            shot: P + 't6-before.png',
            alt: 'The Marking Guide and Rubric Composition tab showing the composition derived from the final demand values, with the clinical reflection at CLO 1 20.7%, CLO 2 34.5%, CLO 3 13.8%, CLO 4 31.0%.',
            cap: 'Composition derived from the final demand values.',
          },
          { k: 'brief',
            title: 'What moved inside an assignment that did not move',
            body: ['The total is identical. The composition is not.'],
            figures: {
              title: 'Clinical reflection · what each outcome attracts',
              cols: ['CLO', 'Before', 'After', 'Change'],
              rows: [
                ['CLO 1 · clinical reasoning', '20.7%', '20.7%', 'none'],
                ['CLO 2 · patient-centred care', '34.5%', '34.5%', 'none'],
                { c: ['CLO 3 · evidence-based practice', '20.7%', '13.8%', 'minus 7'], k: 'asg' },
                { c: ['CLO 4 · professional communication', '24.1%', '31.0%', 'plus 7'], k: 'asg' },
              ],
              note: 'Two outcomes have traded roughly seven percentage points inside an assignment whose overall weighting did not change at all.',
            },
          },
          { k: 'note',
            body: ['Priya: “Clinical reasoning and patient-centred care haven\u2019t moved at all. But evidence-based practice has dropped from about 21% to 14%, and professional communication has gone from 24 up to 31. Seven points each way, inside an assignment whose total didn\u2019t change.”'],
            principle: { name: 'A stable total can hide a shifted rubric', text: 'Tab 5 reports each assignment\u2019s overall weighting; Tab 6 reports what each outcome attracts inside it. Changes in different rows can offset each other at the assignment level while moving the composition underneath substantially. Check every assignment whose rows changed, not only the ones whose totals shifted.' },
          },
          { k: 'brief',
            title: 'The rubric Priya brought',
            body: [
              'Before you compare anything: Tab 6\u2019s figures are estimates, not exact targets. A gap of about five points or more is what is worth chasing; anything under that is noise.',
              'Two of her three criteria map to a single outcome, so they are straightforward. The third carries two at once.',
            ],
            figures: {
              title: 'Current rubric · clinical reflection, 100 marks',
              cols: ['Criterion', 'Marks', 'Mapped to'],
              rows: [
                ['Clinical decision-making described', '20', 'CLO 1'],
                ['Patient-centred approach demonstrated', '35', 'CLO 2'],
                ['Reflective writing quality (evidence use and professional voice)', '45', 'CLO 3 + CLO 4'],
              ],
            },
          },
          { k: 'probe',
            question: 'Reflective writing quality is 45 marks across two outcomes. What do you need to ask Priya before you can tell whether it is correctly weighted?',
            qb: 'implicit-weighting',
            why: 'Because the split between the two is a judgement she already makes every time she marks, and it has never been written down. Ask how she marks it in practice, not how she thinks it should be marked.',
          },
          { k: 'note',
            body: ['Her answer: “About 45 per cent evidence use, 55 per cent reflective voice. That\u2019s how I\u2019ve marked it for years.” Out of 100 marks, that puts CLO 3 at 20.3% of the assignment and CLO 4 at 24.8%. Against the original Tab 6 figures of 20.7% and 24.1% it was a close match. It was never revisited when the mapping changed.'] },
          { k: 'brief',
            title: 'Close the gap',
            body: [
              'Tab 6 now wants 13.8% from CLO 3 and 31.0% from CLO 4. The 45 marks stay where they are; what changes is the balance inside the criterion, and therefore the marking guidance Priya writes for it.',
              'Work out the internal balance that lands those two figures, to the nearest five per cent.',
            ],
            figures: {
              title: 'What the criterion has to deliver',
              cols: ['CLO', 'As marked now', 'Tab 6 wants', 'Gap'],
              rows: [
                ['CLO 3 · evidence use', '20.3%', '13.8%', 'plus 6'],
                ['CLO 4 · professional voice', '24.8%', '31.0%', 'minus 6'],
              ],
              note: 'The criterion is worth 45 marks out of 100, so its internal balance converts directly into percentages of the assignment.',
            },
          },
          { k: 'entry',
            tab: 'Tab 6',
            title: 'Set the internal balance',
            derive: true,
            unit: '%',
            body: ['Two numbers totalling 100, to the nearest five.'],
            groups: [{ label: 'Inside the reflective writing criterion', inputs: [
              { id: 'p6b1', label: 'CLO 3 · critical use of evidence', expect: 30 },
              { id: 'p6b2', label: 'CLO 4 · professional reflective voice', expect: 70 },
            ] }],
          },
          { k: 'result',
            tab: 'Tab 6 · recalibrated',
            readout: {
              title: 'Where each outcome lands at 30 / 70',
              cols: ['CLO', 'Now attracts', 'Tab 6 wants', 'Gap'],
              rows: [
                ['CLO 3 · evidence-based practice', '13.5%', '13.8%', 'under half a point'],
                ['CLO 4 · professional communication', '31.5%', '31.0%', 'under half a point'],
              ],
              note: 'Both within half a point, with no marks moved between criteria. Only the marking guidance changes.',
            },
          },
          { k: 'probe',
            question: 'The numbers are closed. Is there a reason to restructure the criterion anyway?',
            qb: 'two-ways-to-close',
            why: 'Because offering both options separates the arithmetic fix from the rubric-design judgement. Most academics take the option that leaves the rubric document alone, and separating the criterion stays available as a later decision rather than a precondition.',
          },
          { k: 'note',
            body: [
              'Priya: “A criterion asking markers to weigh two quite different things at roughly 30/70 is harder to apply consistently than one doing a single job. I\u2019d separate it for that reason, not this one. For now, updating the marking guidance gets the numbers back in line without waiting on a formal rubric revision.”',
              'She sets the balance at 30 / 70 for this teaching period and flags the criterion for a proper split before the rubric next needs committee approval. Then she and Kate do the same walk-through for the care plan, where clinical reasoning climbs from 16.1% to 29.4% while patient-centred care falls from 35.7% to 24.5%, and for the exam, where professional communication goes to zero and the criterion carrying it comes out of the rubric entirely.',
              'Her own summary: “Three rubrics, and the only one I would have thought to check on my own is the exam, because that\u2019s the assignment that looks different. The reflection is the one I would have left alone.”',
            ],
          },
        ],
      },
      {
        n: 3,
        title: 'The sequence',
        aim: 'Now the teaching. The assessment decisions are fixed, so they set the specification: work backwards from the minimum readiness each assignment requires and build the weeks that deliver it.',
        blocks: [
          { k: 'brief',
            title: 'What the tool has done while you were not looking',
            body: [
              'Priya never opened Tab 2. When you go there now, it is not empty: the tool has already created the assignments you named in the mapping and placed them in the weeks you gave them.',
              'What it cannot do is invent the teaching. Every week is blank, and each assignment carries the same message.',
            ],
          },
          { k: 'result',
            tab: 'Tab 2 · auto-populated',
            shot: P + 't2-autopopulated.png',
            alt: 'The Teaching Readiness template with Weeks 1 to 4 present but empty, each offering add CLO and add assignment buttons, and an Assignments section showing Assignment 1, clinical reasoning, at Week 4 with the message: No CLO has been taught by this point. Add teaching readiness before mapping assignment CLOs.',
            cap: '“No CLO has been taught by this point. Add teaching readiness before mapping assignment CLOs.” That is the assessment-first path catching up with itself.',
          },
          { k: 'brief',
            title: 'The specification you already wrote',
            body: [
              'You do not have to guess what the sequence needs to deliver. You set it in Iteration 1. Every demand value produced a minimum readiness marker, and those markers are the brief.',
              'Read them off the mapping for the clinical reflection in Week 4. Whatever teaching goes into Weeks 1 to 3 has to get each outcome at least this far.',
            ],
            figures: {
              title: 'Minimum readiness required by Week 4',
              cols: ['CLO', 'Demand at the reflection', 'Minimum readiness'],
              rows: [
                ['CLO 1 · clinical reasoning', '15% of its budget', '15%'],
                ['CLO 2 · patient-centred care', '30% of its budget', '30%'],
                ['CLO 3 · evidence-based practice', '10% of its budget', '10%'],
                { c: ['CLO 4 · professional communication', '45% of its budget', '45%'], k: 'asg' },
                ['', 'and by the care plan in Week 8', 'CLO 1 55% · CLO 2 70% · CLO 3 45% · CLO 4 100%'],
              ],
              note: 'CLO 4 is the demanding one, and it is demanding because of a decision you made in Iteration 1: giving the reflection 45% of professional communication, so the care plan could finish the job and the exam could drop it entirely.',
            },
          },
          { k: 'brief',
            title: 'The weeks before the reflection',
            body: [
              'Weeks 5 onward are already drafted and hold up fine, so the work is in Weeks 1 to 3. Here is what Priya has planned for them, and what each week gets each outcome to.',
              'Enter the readiness each outcome reaches by the end of Week 3, which is what the reflection in Week 4 will be assessed against.',
            ],
            figures: {
              title: 'Tab 2 · Weeks 1 to 3 as drafted',
              cols: ['Week', 'Teaching focus', 'Builds'],
              rows: [
                ['Week 1', 'Foundations of clinical assessment', 'CLO 1, CLO 2'],
                ['Week 2', 'Patient interviewing and person-centred practice', 'CLO 2'],
                ['Week 3', 'Electronic health record (EHR) orientation', 'no outcome under pressure at the reflection'],
                { c: ['Week 4', 'Clinical reflection due', 'assesses all four outcomes'], k: 'asg' },
              ],
              note: 'Readiness reached by the end of Week 3: CLO 1 55%, CLO 2 36%, CLO 3 19%, CLO 4 30%.',
            },
          },
          { k: 'entry',
            tab: 'Tab 2',
            title: 'Record readiness at Week 4',
            unit: '%',
            groups: [{ label: 'Taught by Week 4', inputs: [
              { id: 'p2r1', label: 'CLO 1', expect: 55 },
              { id: 'p2r2', label: 'CLO 2', expect: 36 },
              { id: 'p2r3', label: 'CLO 3', expect: 19 },
              { id: 'p2r4', label: 'CLO 4', expect: 30 },
            ] }],
          },
          { k: 'result',
            tab: 'Tab 4 · the bars fill in',
            readout: {
              title: 'Three clear, one short',
              cols: ['CLO', 'Minimum required', 'Sequence delivers', 'Verdict'],
              rows: [
                ['CLO 1', '15%', '55%', 'clears'],
                ['CLO 2', '30%', '36%', 'clears'],
                ['CLO 3', '10%', '19%', 'clears'],
                { c: ['CLO 4', '45%', '30%', 'fifteen points short'], k: 'asg' },
              ],
              flag: 'The purple bars have appeared at last, and three of the four sit past their markers. CLO 4 does not.',
            },
          },
          { k: 'probe',
            question: 'The tool offers to lower the readiness level to match the demand. Would you take it? If not, what is the other lever?',
            qb: 'accept-the-suggestion',
            why: 'Because the option the tool surfaces is the one the academic will default to, and it is often the wrong one. A firm refusal is the useful answer: it rules out one lever and forces attention onto the teaching sequence, which is where the real decision lives.',
          },
          { k: 'note',
            body: ['Priya refused it: “Reflective writing is exactly where I\u2019d want professional communication showing up early. Foundational at 30% feels too thin for what I\u2019m asking of the reflection.” Which leaves what is taught in Weeks 1 to 3.'] },
          { k: 'brief',
            title: 'An aside worth having: what is already in the sequence',
            body: [
              'The teaching that would lift CLO 4 exists. It is just in the wrong place. A session on structured clinical documentation sits in Week 6, two weeks after the assignment that assesses the outcome it builds.',
              'Meanwhile Week 3 holds the EHR orientation, which supports nothing under pressure at the reflection. Students do not touch the electronic health record for anything assessed until the care plan in Week 8.',
            ],
            figures: {
              title: 'Tab 2 · Weeks 3 to 8',
              cols: ['Week', 'Session', 'Builds'],
              rows: [
                ['Week 3', 'Electronic health record (EHR) orientation', 'nothing due yet'],
                { c: ['Week 4', 'Clinical reflection due', 'assesses CLO 4 at 45%'], k: 'asg' },
                ['Week 5', 'Consolidation and feedback, no new content', 'room here'],
                ['Week 6', 'Structured clinical documentation', 'CLO 4'],
                ['Week 7', 'Care planning frameworks', 'CLO 2'],
                { c: ['Week 8', 'Care plan due', 'first assessed use of the EHR'], k: 'asg' },
              ],
              note: 'Week 5 is the only week between the two assignments with room in it.',
            },
          },
          { k: 'entry',
            tab: 'Tab 2',
            title: 'Resequence',
            derive: true,
            body: [
              'Move the clinical documentation session to the week that clears the conflict, then place the EHR orientation it displaces.',
              'Weeks 6 and 7 are committed to content other outcomes depend on, and the EHR session needs to land before the care plan that first assesses its use.',
            ],
            groups: [{ label: 'Moves to Week', inputs: [
              { id: 'p2w1', label: 'Structured clinical documentation', expect: 3 },
              { id: 'p2w2', label: 'EHR orientation', expect: 5 },
            ] }],
          },
          { k: 'result',
            tab: 'Tab 4 · conflict resolved',
            readout: {
              title: 'All four bars clear',
              cols: ['CLO', 'Minimum required', 'Now delivers', 'Verdict'],
              rows: [
                ['CLO 1', '15%', '55%', 'clears'],
                ['CLO 2', '30%', '36%', 'clears'],
                ['CLO 3', '10%', '19%', 'clears'],
                ['CLO 4', '45%', '60%', 'clears, Developing'],
              ],
              note: 'With documentation taught in Week 3, CLO 4 readiness at Week 4 lifts from Foundational at 30% to Developing at 60%.',
            },
          },
          { k: 'probe',
            question: 'The conflict is closed. What has the swap cost, and what question has nobody asked yet?',
            qb: 'something-has-to-move-out',
            why: 'Because this is the question the academic will not ask themselves. The conflict is fixed, everyone is relieved, and the displaced content gets placed by accident rather than on purpose. Asked here, the displaced session gets reassessed on its own merits.',
          },
          { k: 'note',
            body: [
              'The EHR orientation moved to Week 5, the only week with room before the care plan that actually needs it, and far closer to the point of use than Week 3 ever was. The swap did not only clear the conflict; it gave a session that had been sitting in Week 3 by habit a defensible reason to be where it is.',
              'That rationale is the real output. Most course documents record which outcome is mapped to which week, but not whether the mapping is achievable by then. The claim rests on intuition, unverified. What Priya now has is a specific readiness figure at a specific week, written down, that the whole teaching team can work from.',
            ],
            principle: { name: 'Resequencing', text: 'Moving content to clear a conflict is never free. Whatever occupied that week has to go somewhere, and deciding where is itself a design decision, worth making deliberately rather than by default.' },
          },
          { k: 'note',
            title: 'One last thing about going in this order',
            body: [
              'Resequencing teaching is not the only lever available in Tab 2. You can also move an assignment: if there genuinely is not enough time to teach something before the reflection, pushing the reflection from Week 4 to Week 6 solves the readiness problem outright.',
              'But an assignment is not just a date. Moving it changes which weeks sit before it, which changes the readiness available at it, which changes whether the demand you set in Tab 4 still makes sense there. The markers you were working to were derived from a Week 4 reflection.',
              'So if you move an assignment here, go back to the mapping and read it again. That is the loop the assessment-first order has to close, and it is the one cost of starting at the other end.',
            ],
          },
        ],
      },
    ],
  };

  /* ─── Bonus · Aisha · Psychology · the cause is upstream ─── */

  const AISHA = {
    id: 'aisha',
    eyebrow: 'One more thing worth knowing',
    title: 'Sometimes the fix is not in Tab 4 at all',
    discipline: 'Psychology · third year',
    blurb: 'A short one. Both examples above fixed an alignment problem by changing the mapping or the teaching. This is the case where neither can help.',
    blocks: [
      { k: 'brief',
        title: 'The course',
        body: [
          'Aisha coordinates third-year Research Methods. Her three assignments are a research proposal at 30%, a data analysis report at 40%, and a critical review at 30%. Each assignment is the primary vehicle for a different outcome, and the critical review is where critical evaluation is meant to live.',
          'Her mapping is already tidy. Enter it and read what the tool says.',
        ],
        figures: {
          title: 'Tab 1 and Tab 4, the figures to enter',
          cols: ['CLO', 'Weighting', 'Proposal', 'Data report', 'Critical review'],
          rows: [
            ['CLO 1 · research design', '40%', '75', '15', '10'],
            ['CLO 2 · statistical reasoning', '40%', '10', '80', '10'],
            ['CLO 3 · critical evaluation', '20%', '5', '15', '80'],
          ],
        },
      },
      { k: 'entry',
        tab: 'Tab 1 + Tab 4',
        title: 'Enter the weightings and the demand',
        columns: ['Weighting %', 'Proposal', 'Data report', 'Critical review'],
        groups: [
          { label: 'CLO 1', inputs: [{ id: 'a1', expect: 40 }, { id: 'a2', expect: 75 }, { id: 'a3', expect: 15 }, { id: 'a4', expect: 10 }] },
          { label: 'CLO 2', inputs: [{ id: 'a5', expect: 40 }, { id: 'a6', expect: 10 }, { id: 'a7', expect: 80 }, { id: 'a8', expect: 10 }] },
          { label: 'CLO 3', inputs: [{ id: 'a9', expect: 20 }, { id: 'a10', expect: 5 }, { id: 'a11', expect: 15 }, { id: 'a12', expect: 80 }] },
        ],
      },
      { k: 'result',
        tab: 'Tab 5 · Assignment Weightings',
        readout: {
          title: 'What the mapping implies',
          cols: ['CLO', 'Proposal', 'Data report', 'Critical review'],
          rows: [
            ['CLO 1', '30.00%', '6.00%', '4.00%'],
            ['CLO 2', '4.00%', '32.00%', '4.00%'],
            ['CLO 3', '1.00%', '3.00%', '16.00%'],
          ],
          totals: ['35.00%', '41.00%', '24.00%'],
          note: 'Grand total 100.00%',
        },
        headline: { label: 'Implied distribution (proposal / data report / critical review)', value: '35.00 / 41.00 / 24.00', note: 'against the intended 30 / 40 / 30, the critical review is six points light' },
      },
      { k: 'brief',
        title: 'Push the mapping as hard as it will go',
        body: ['The obvious move is to concentrate critical evaluation on the critical review. So do not do it by halves: put the whole of CLO 3 there. Nothing at the proposal, nothing at the data report, all of it at the review. That is as concentrated as a row can possibly get.'],
      },
      { k: 'entry',
        tab: 'Tab 4',
        title: 'Take CLO 3 to its maximum',
        columns: ['Proposal', 'Data report', 'Critical review'],
        groups: [{ label: 'CLO 3', inputs: [{ id: 'a13', expect: 0 }, { id: 'a14', expect: 0 }, { id: 'a15', expect: 100 }] }],
      },
      { k: 'result',
        tab: 'Tab 5 · at maximum concentration',
        readout: {
          title: 'The most the mapping can do',
          cols: ['CLO', 'Proposal', 'Data report', 'Critical review'],
          rows: [
            ['CLO 1', '30.00%', '6.00%', '4.00%'],
            ['CLO 2', '4.00%', '32.00%', '4.00%'],
            ['CLO 3', '0.00%', '0.00%', '20.00%'],
          ],
          totals: ['34.00%', '38.00%', '28.00%'],
          note: 'Grand total 100.00%',
        },
        headline: { label: 'Implied distribution', value: '34.00 / 38.00 / 28.00', note: 'the critical review still falls short of 30, and the data report has now dropped below 40 as well' },
      },
      { k: 'probe',
        question: 'The row has nowhere further to go, and the critical review still cannot reach 30. What does that tell you, and what would you ask Aisha now?',
        qb: 'nowhere-further-to-go',
        why: 'Because every remaining move in Tab 4 makes something else worse. When a row is maxed out and the number still will not reach, the constraint is not the mapping, it is the size of the budget the mapping is distributing.',
      },
      { k: 'note',
        body: ['CLO 3 is weighted at 20% of the course. Even if the critical review were the only place it was ever assessed, the most it could contribute is 20 points, and the review needs 30. No arrangement of Tab 4 can produce a number larger than the budget Tab 1 gave it, and no amount of resequencing teaching will change that either.'],
        principle: { name: 'The ceiling is upstream', text: "An outcome's total contribution across all assignments can never exceed its Tab 1 weighting. When an assignment cannot reach its intended share even at maximum concentration, the mapping is not the problem, the weighting is. Go back a tab." },
      },
      { k: 'brief',
        title: 'The fix, one tab earlier',
        body: ["Aisha's mapping was right all along. What was wrong was a stated belief: critical evaluation is a third of what this course is about, and it had been written down as a fifth. Restore the original demand values, and change Tab 1 instead."],
        figures: {
          title: 'Tab 1 · revised weightings',
          cols: ['CLO', 'Was', 'Now'],
          rows: [
            ['CLO 1 · research design', '40%', '35%'],
            ['CLO 2 · statistical reasoning', '40%', '35%'],
            ['CLO 3 · critical evaluation', '20%', '30%'],
          ],
        },
      },
      { k: 'entry',
        tab: 'Tab 1',
        title: 'Revise the weightings',
        unit: '%',
        groups: [{ label: 'Course weighting', inputs: [
          { id: 'a16', label: 'CLO 1', expect: 35 },
          { id: 'a17', label: 'CLO 2', expect: 35 },
          { id: 'a18', label: 'CLO 3', expect: 30 },
        ] }],
        body: ['Leave Tab 4 exactly as Aisha originally had it: 75 / 15 / 10, 10 / 80 / 10, 5 / 15 / 80.'],
      },
      { k: 'result',
        tab: 'Tab 5 · after the Tab 1 revision',
        readout: {
          title: 'The same mapping, a different budget',
          cols: ['CLO', 'Proposal', 'Data report', 'Critical review'],
          rows: [
            ['CLO 1', '26.25%', '5.25%', '3.50%'],
            ['CLO 2', '3.50%', '28.00%', '3.50%'],
            ['CLO 3', '1.50%', '4.50%', '24.00%'],
          ],
          totals: ['31.25%', '37.75%', '31.00%'],
          note: 'Grand total 100.00%',
        },
        headline: { label: 'Implied distribution', value: '31.25 / 37.75 / 31.00', note: 'the critical review clears 30 for the first time, without a single demand value changing' },
      },
      { k: 'note',
        body: [
          'Aisha did not redesign her course. She corrected what she had written down about it. The mapping had been driving her teaching, her assessment design and her resourcing correctly the whole time; the CLO weighting was the one thing that had never caught up.',
          'That distinction matters well beyond the tool. A 20% weighting on critical evaluation sends a very different signal in programme mapping, assurance-of-learning reporting and accreditation submissions than a 30% one does, and hers had been understating the course for years.',
        ],
      },
    ],
  };

  /* ─── Closing · what these decisions cost outside the tool ─── */

  const CLOSING = {
    eyebrow: 'Before you close the tool',
    title: 'What a mapping decision costs',
    blurb: 'Every change you just made has a consequence somewhere other than the tool. The download at the end of a session exists so those consequences can be worked through rather than discovered later.',
    groups: [
      { label: 'Assessment load and student effort',
        text: "Priya's original mapping implied a case study exam carrying just over half the grade against a course students had been told was 20 / 40 / 40. The revision moved it to 21.75 / 40.75 / 37.50. That is not a numerical tidy-up: it changes what students are actually being asked to do, and when." },
      { label: 'Teaching sequence',
        text: "Priya's clinical documentation session moves from Week 6 to Week 3, and the EHR orientation it displaces moves to Week 5. Both changes need to reach the LMS release schedule and the affected run sheets before the teaching period they apply to." },
      { label: 'Tutorial and workshop activity',
        text: 'Tutors covering the moved weeks need briefing on new content before the semester the change takes effect. A session that moves earlier is a session someone has to be ready to teach earlier.' },
      { label: 'LMS resources',
        text: 'Reading lists, recordings and activity pages follow the sequence. When content moves week, so does everything released alongside it.' },
      { label: 'Feedback',
        text: "Priya's deliberate zero makes the care plan the last formal feedback students receive on professional communication. Feedback that used to be provisional, with the exam still to come, now has to be complete." },
      { label: 'Marking guide and rubric',
        text: "Every assignment whose rows moved has a rubric to re-check, including the ones whose overall weighting barely changed. Priya's clinical reflection sat at 21.75% before and after, while two outcomes traded seven points inside it." },
    ],
    coda: {
      title: 'Both starting points are legitimate',
      body: [
        'David built the teaching sequence first and let the mapping describe it. Priya mapped the assessment first and made teaching deliver it. Neither is the correct order, and the tool takes no position on which you should use. The two examples exist in this tutorial specifically to show that.',
        'The orders are not identical in cost, though, and it is worth being honest about the difference. Going teaching-first, the readiness bars are populated before any demand is entered, so conflicts surface as you map. Going assessment-first, the bars stay empty until the end, and every minimum readiness marker you generated becomes a specification the sequence has to satisfy afterwards. Same three stages, same arithmetic, more back-and-forth at the end.',
        'What the tool does insist on is that the two be reconciled. A mapping that teaching cannot deliver is a plan for a course nobody can run; a teaching sequence that no mapping reflects is a course nobody can describe. Whichever end you start from, the other end still has to answer.',
      ],
    },
  };

  window.TUTORIAL_A = { examples: [DAVID, PRIYA], bonus: AISHA, closing: CLOSING };
})();
